"""empty message

Revision ID: 92d6c83ac5d3
Revises: 
Create Date: 2024-11-21 22:29:39.781642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92d6c83ac5d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_preference', schema=None) as batch_op:
        batch_op.drop_constraint('gym_preference_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('social_media_platform')
        batch_op.drop_column('preferred_contact_method')
        batch_op.drop_column('social_media_handle')
        batch_op.drop_column('phone')

    with op.batch_alter_table('workout_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_preference_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('workout_schedule_user_id_day_of_week_time_slot_key', type_='unique')
        batch_op.create_unique_constraint(None, ['gym_preference_id', 'user_id', 'day_of_week', 'time_slot'])
        batch_op.create_foreign_key(None, 'gym_preference', ['gym_preference_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('workout_schedule_user_id_day_of_week_time_slot_key', ['user_id', 'day_of_week', 'time_slot'])
        batch_op.drop_column('gym_preference_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_media_handle', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_contact_method', postgresql.ENUM('PHONE', 'EMAIL', 'SOCIAL_MEDIA', name='preferredcontactmethod'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_media_platform', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('gym_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('gym_preference_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
