"""empty message

Revision ID: eaf1374d63de
Revises: 92d6c83ac5d3
Create Date: 2024-11-21 22:35:05.617542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf1374d63de'
down_revision = '92d6c83ac5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_gym_preferences')
    with op.batch_alter_table('gym_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_contact_method', sa.Enum('PHONE', 'EMAIL', 'SOCIAL_MEDIA', name='preferredcontactmethod'), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('social_media_handle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('social_media_platform', sa.String(), nullable=True))

    with op.batch_alter_table('workout_schedule', schema=None) as batch_op:
        batch_op.drop_constraint('workout_schedule_gym_preference_id_user_id_day_of_week_time_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_id', 'day_of_week', 'time_slot'])
        batch_op.drop_constraint('workout_schedule_gym_preference_id_fkey', type_='foreignkey')
        batch_op.drop_column('gym_preference_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_preference_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('workout_schedule_gym_preference_id_fkey', 'gym_preference', ['gym_preference_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('workout_schedule_gym_preference_id_user_id_day_of_week_time_key', ['gym_preference_id', 'user_id', 'day_of_week', 'time_slot'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('social_media_platform')
        batch_op.drop_column('social_media_handle')
        batch_op.drop_column('phone')
        batch_op.drop_column('preferred_contact_method')

    with op.batch_alter_table('gym_preference', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_gym_preferences',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gym_preference_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gym_preference_id'], ['gym_preference.id'], name='user_gym_preferences_gym_preference_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_gym_preferences_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'gym_preference_id', name='user_gym_preferences_pkey')
    )
    # ### end Alembic commands ###
